harvard-lil/h2o

- .coveralls.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- test/test_helper.rb
- Badge is pointed to Master so can't show coverage % for this branch right now
- Needed to branch off of this repo, not mine, so that I could see it working on Coveralls.
> Install Coveralls for Coverage %

- app/assets/stylesheets/forms.scss
> Revert "Delete padding & set form height b/c wasn't showing up in Firefox."

- app/assets/javascripts/lib/ui/search.js.erb
- app/assets/stylesheets/searches.scss
- app/controllers/searches_controller.rb
- app/models/case.rb
- app/models/content/casebook.rb
- app/models/user.rb
- app/views/searches/_results.html.erb
- app/views/searches/show.html.erb
- lib/locales/en/search.yml
- test/fixtures/cases.yml
- test/fixtures/content_nodes.yml
* Fix filter selected text not showing up on initial page load
* Add filters for cases & users, filters stay selected while navigating between tabs
* Filters only show options from search results ( add solr configs ) 
* Render 'no result' heading when 0 search results
* Render citations in case search results
* Fix sort by date
> Finish search filtering 

- app/assets/stylesheets/landing.scss
- app/views/base/index.html.erb
- lib/locales/en/landing.yml
- test/system/content_test.rb
Filling in some landing page text.
> Landing page copy

- app/controllers/searches_controller.rb
> Revert "Check for existence of owner affiliation while building casebook filt…"

- app/controllers/content/node_controller.rb
- app/views/content/_actions.html.haml
- app/views/content/layout.html.erb
- app/views/content/sections/_search_result.html.erb
- app/views/content/show.html.erb
- lib/htmltoword/xslt/base.xslt
- lib/htmltoword/xslt/h2o/export.xslt
- fixes a bug preventing exports with certain replacement annotations from opening in Word
- fixes a bug when adding a resource under a specific section
> bugfixes for docx export, add resource 

- app/assets/stylesheets/casebook.scss
- app/views/content/resources/show.html.erb
- app/views/content/table_of_contents/_edit.haml
- app/views/content/table_of_contents/_show.haml
- lib/locales/en/content.yml
Collects a few, mostly stylistic issues re casebook items.
- closes #104 
- closes #103 
- closes #102
> Casebook listing styles

- .gitignore
- README.md
I was curious to try out the new H2O code! Got it running with a couple of tweaks to the installation instructions -- thanks to @emmalemma for help debugging the solr issue.
> Update installation instructions

- app/views/content/casebooks/export.haml
- app/views/content/sections/export.haml
- lib/htmltoword/xslt/base.xslt
- lib/htmltoword/xslt/cleanup.xslt
- lib/htmltoword/xslt/h2o/export.xslt
Re-closes issues #123 and #131
> export bugfixes for BlockQuote and CaseHeader

- app/controllers/users_controller.rb
> Verify user bug

- app/views/content/_tabs.html.haml
- app/views/content/edit_details.html.erb
* Add back edit_details tab
* Fix reset button
> Edit details for textblocks & links ( defaults ) 

- app/assets/javascripts/lib/ui/content/annotations/footnotes.js
- app/assets/javascripts/lib/ui/content/annotations/index.js
- app/assets/stylesheets/content/annotations.scss
- app/models/content/casebook.rb
- app/models/content/node.rb
- db/migrate/20170911044044_make_content_deletes_cascade.rb
- db/schema.rb
- migration and settings to properly destroy casebooks
- visual fix for highlights overlapping text
- JS to handle footnotes that link to elided or replaced content
> Tweaks for issue #140

- app/assets/javascripts/lib/ui/content/add_content.js.erb
- app/assets/stylesheets/content/modals.scss
- app/controllers/content/sections_controller.rb
https://trello.com/c/eobfcaoT/61-fix-text-editor-on-add-resource-add-text
> Fix text editor bugs

- app/controllers/content/casebooks_controller.rb
- app/models/content/node.rb
- app/models/default.rb
* Only have ancestry in casebook model
* Users can clone their own casebooks & preserve ancestry
> Ancestry fixes

- lib/migrate.rb
> Revert "Add default & textblock to setting actual_object_type."

- lib/locales/en/content.yml
Tiny change to improve placeholder text
> Corrected: placeholder text in casebook/section details form

- app/models/content/child.rb
- app/models/content/concerns/has_children.rb
casebook.contents has data from before the resource/section is destroyed - so passing in the child itself allows you to check if it's been deleted.
> Deleting section reflow ordinals

- db/schema.rb
Remove index on case full_name - migration from May not sure why it's processed now.
> Schema change

- app/models/case.rb
- app/views/searches/_results.html.erb
This fixes a typo, and adds a conditional. I'm not sure if this is the right move, or if it would be better to ensure that all cases have decision dates.
> Correct formated_decision_date

- app/assets/stylesheets/header.scss
Tiny CSS change to make user menu accessible on browse view
> Fixed: user dropdown hidden behind search bar on browse view

- app/controllers/content/resources_controller.rb
- app/views/content/_tabs.html.haml
- app/views/content/edit_details.html.erb
- app/views/searches/_results.html.erb
- lib/migrate.rb
- lib/playlist_id_migration_directions.md
* For old h2o cases - merge playlist_item.notes and collage.description into headnotes
* add headnote to cases & make editable
> Case's have headnotes

- app/assets/javascripts/lib/ui/filter-selectize.js
- lib/playlist_id_migration_directions.md
and update playlist_id_migration doc
> Sort by title works 

- app/models/content/resource.rb
- app/models/user.rb
- app/views/content/resources/_embed.haml
- lib/migrate.rb
- lib/playlist_id_migration_directions.md
* Remove destroy dependent associations for user model
* When migrating annotations --- find annotations from annotate_item_id vs collage_id
> Workaround fix so that para numbering only shows one number

- app/views/password_resets/edit.html.erb
- config/initializers/RailsPatch22584.rb
- test/system/users_test.rb
> use simple_form_for instead of form_for 

- app/decorators/content/node_decorator.rb
- app/models/content/child.rb
- app/models/content/node.rb
- app/views/content/casebooks/export.haml
- app/views/content/details.html.erb
- app/views/content/resources/export.haml
- app/views/content/resources/show.html.erb
- app/views/content/sections/export.haml
- app/views/content/show.html.erb
> Call formatted_headnote from node controller, instead of the node_decorator.

- app/decorators/content/node_decorator.rb
- app/models/content/child.rb
- app/models/content/node.rb
- app/views/content/casebooks/export.haml
- app/views/content/details.html.erb
- app/views/content/resources/export.haml
- app/views/content/resources/show.html.erb
- app/views/content/sections/export.haml
- app/views/content/show.html.erb
> Revert "Call formatted_headnote from node controller, instead of the node_decorator."

- app/assets/javascripts/lib/ui/content/clone_modal.js
- app/assets/javascripts/lib/ui/content/revise_modal.js.erb
- app/controllers/content/annotations_controller.rb
- app/services/merge_draft_into_published_casebook.rb
- Will add back when turbolinks are removed.
> Comment out clone and revise modal.

- app/views/content/layout.html.erb
> Revert "Cache table of content edit views."

- lib/htmltoword/xslt/base.xslt
The content of a list in a headnote wasn't showing up in docx
> in export lists -  show text.

- Gemfile
- Gemfile.lock
- README.md
I thought it might be useful to add yesterday's discoveries to the README. This also removes rmultimarkdown, per your advice Wednesday.
> Notes on fresh installation

- lib/locales/en/landing.yml
- correct sample book links on landing page
- select different image for prof
> Small corrections to landing page

- lib/locales/en/landing.yml
Quick fix to bad landing page link
> Corrected featured author link

- app/assets/javascripts/lib/ui/content/export.js.erb
- app/controllers/content/casebooks_controller.rb
- app/controllers/content/resources_controller.rb
- app/controllers/content/sections_controller.rb
- test/system/export_test.rb
> Remove PDF & HTML export options.

- app/assets/javascripts/lib/requests.js
- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/assets/stylesheets/content/annotations.scss
- app/models/content/resource.rb
> Annotations replace pointer & Firefox location 

- app/assets/stylesheets/casebook.scss
Vertically aligns paragraph numbers w/ 1st line of paragraph. Tee hee.
> Ridiculously tiny tweak

- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/controllers/content/annotations_controller.rb
Create annotation as json and return annotation_id to put in href query string.
> annotation-id in URL 

- app/assets/javascripts/lib/ui/content/annotations/index.js
- app/assets/javascripts/lib/ui/content/annotations/replace.js
- app/models/content/annotation.rb
Not just after the creation of replacement annotations.
> Set focus after creation of any new annotation.

- app/assets/javascripts/lib/ui/content/annotations/index.js
- app/assets/javascripts/lib/ui/content/annotations/note.js
- app/assets/stylesheets/content/annotations.scss
- Remove double underline from text that is selected for open notes
- selected text is equally selected amongst paragraph lines
- the new annotation menu doesn't pop up when clicking the selected text
> Annotation notes 2

- app/assets/stylesheets/landing.scss
- app/assets/stylesheets/variables.scss
- app/views/layouts/application.html.erb
- app/views/layouts/iframe.html.erb
- app/views/layouts/main.html.erb
> 376 replace landing page font

- app/assets/stylesheets/dashboard.scss
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/mixins.scss
- app/views/content/dashboard/_content_browser.html.erb
> 285 handle reasonable text lengths

- app/assets/stylesheets/landing.scss
In response to @anastasia https://github.com/harvard-lil/h2o/issues/376#issuecomment-400427846
> Increase leading on landing page headlines

- app/decorators/content/node_decorator.rb
> Remove improper @ scoping

- app/views/searches/_results.html.erb
> Add a no-results response to search partial

- app/views/content/table_of_contents/_edit.haml
- app/views/content/table_of_contents/_show.erb
- lib/locales/en/content.yml
> In table of contents links have the correct content tag

- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/assets/stylesheets/content/annotations.scss
Some minor tweaks to make annotation menus and forms a little less cryptic.
> Annotation menu simplification

- lib/migrate.rb
- lib/migration_notes/june-18-old-h2o-to-new-h2o-data-queries.sql
Remove the preexisting_casebook check in the migrating script
> Migrating text blocks

- app/views/layouts/main.html.erb
Changed from {controller_name} to "Open Casebooks" to be a little more user friendly
> Tiny change to default title name 

- app/models/content/resource.rb
- app/services/apply_annotation_to_paragraphs.rb
This doesn't fix the double elisions ticket, only adding back lines that were in the original annotation script.
> Bug from export ticket: multiple elisions do not show up,

- app/decorators/content/node_decorator.rb
- lib/locales/en/content.yml
> Fix bug: when casebook is draft of published casebook, and casebook is in preview mode - revise button does not create new  casebook

- app/assets/javascripts/lib/ui/content/annotations/elide.js
closes https://github.com/harvard-lil/h2o/issues/392#issuecomment-410812798
> Allow for nested elements within elision; add comments.

- app/services/apply_annotation_to_paragraphs.rb
> Show note content wrapper in preview and published mode.

- app/views/content/table_of_contents/_edit.erb
> listing-section data-ordinals is filled in correctly.

- app/assets/javascripts/lib/ui/content/dragging.js.erb
- app/controllers/content/sections_controller.rb
- config/routes.rb
- package.json
> Moving sections in sections does not redirect to full casebook layout 

- app/models/content/node.rb
- https://guides.rubyonrails.org/5_2_release_notes.html#active-record-notable-changes
- https://github.com/rails/rails/pull/27790
> Rails params .each now acts like Hash .each in Rails 5.2

- app/services/url_domain_formatter.rb
- test/services/url_domain_formatter_test.rb
> Don't strip out uri.path with urls

- config/initializers/capapi.rb
> Get CAP API location from env var

- app/assets/stylesheets/casebook.scss
- lib/html_helpers.rb
- test/lib/html_helpers_test.rb
#508
Add custom center class
Don't unest div tags in HtmlHelper when using Nokogiri
> Remove deprecated center tags

- app/controllers/content/sections_controller.rb
I believe this is dead given that there's no 'content/sections/new'
template to be rendered.
> Remove unused controller action

- app/assets/javascripts/lib/ui/content/annotations/replace.js
> Revert "Tab accessibility and saving replace annotation on enter coexist."

- app/models/ability.rb
- app/models/role.rb
- config/initializers/rails_admin.rb
> Admin can create user 

- app/views/layouts/_footer.html.erb
- lib/locales/en/footer.yml
- package-lock.json
just hardcoded links to the new guide and blog
> change links in footer

- app/models/ability.rb
- app/models/case.rb
- app/models/default.rb
- app/models/text_block.rb
- app/views/rails_admin/main/_delete_notice.html.erb
- app/views/rails_admin/main/delete.html.erb
- test/fixtures/cases.yml
- test/fixtures/defaults.yml
- test/fixtures/text_blocks.yml
- test/system/admin_test.rb
> Admin deleting case, text block, link tests.

- app/models/ability.rb
- app/views/rails_admin/main/delete.html.erb
- config/initializers/rails_admin.rb
#567 
- refactor show_in_app while in there to remove TextBlock and Default logic
> Admin "Are you sure you want to delete" page associations link to owner view of object

- app/assets/stylesheets/rails_admin/custom/theming.scss
- app/models/content/casebook.rb
- app/views/rails_admin/main/manage_collaborators.html.erb
> Update collaborator works on initial page load & styling for collaborator blocks

- app/views/pages/faq.html.erb
FAQ hadn't been updated since we moved to the new design.
> FAQ language updates

- app/views/base/index.html.erb
- app/views/pages/faq.html.erb
last misspelling corrections for FAQ
> misspelling corrections

- app/webpacker/components/AnnotationBase.vue
- app/webpacker/components/ElisionAnnotation.vue
- app/webpacker/components/NoteAnnotation.vue
- app/webpacker/components/ReplacementAnnotation.vue
- app/webpacker/store/modules/annotations.js
- config/initializers/capapi.rb
Fixes https://github.com/harvard-lil/h2o/issues/642#issuecomment-457593956
> Fix hiding of section numbers

- app/webpacker/components/FootnoteLink.vue
- app/webpacker/components/ResourceSection.js
- app/webpacker/components/TheResourceBody.vue
- app/webpacker/libs/html_helpers.js
- app/webpacker/store/modules/footnotes_ui.js
Trying to parse out the ID was brittle because different cases use
different id structures.
> Make footnote parsing more flexible

- app/models/content/node.rb
- app/models/content/resource.rb
- app/views/content/table_of_contents/_edit.erb
- app/views/content/table_of_contents/_show.erb
- test/system/casebooks_test.rb
> Custom case title shows up in table of contents 

- README.md
- app/controllers/password_resets_controller.rb
- app/mailers/notifier.rb
- app/views/notifier/welcome_email.html
- config/environments/development.rb
> Send welcome email to user after they sign up & create their password 

- app/assets/stylesheets/casebook.scss
- app/views/content/table_of_contents/_edit.erb
- app/views/content/table_of_contents/_show.erb
Use CSS grid to standardize table of contents resource metadata locations
> 699 standardize layout for items content page

- app/assets/stylesheets/casebook.scss
- app/views/content/table_of_contents/_show.erb
#699 
* responsive on mobile
* less margin between citation and year
> TOC responsive styling

- app/assets/stylesheets/casebook.scss
- app/assets/stylesheets/variables.scss
- app/views/content/table_of_contents/_show.erb
#699 
Small padding issues and mobile responsiveness
> Mobile responsiveness 

- app/views/content/table_of_contents/_edit.erb
> Edit mode TOC mobile responsiveness.

- app/webpacker/components/AnnotationBase.vue
- app/webpacker/components/ContextMenu.vue
- app/webpacker/components/TheAnnotator.vue
#673 
- Save temporary ids in store as negative numbers
- Notes and Links are saved optimistically in $store and destroyed when the box loses focus.
> 673 - GUID based annotation 

- app/webpacker/components/AnnotationBase.vue
- app/webpacker/components/NoteAnnotation.vue
> Note annotation underlining shows up in all views

- app/views/notifier/welcome_email.html.erb
> Update link in welcome email.

- app/assets/javascripts/lib/ui/content/save_details.js
- app/decorators/content/node_decorator.rb
- app/services/action_button_builder.rb
- app/views/content/_actions.html.erb
- test/system/casebooks_test.rb
#650 
Put correct get/post requests onto links & buttons
Return button_tags to action_button_builder
Save/cancel buttons don't show up on annotating page ( they do on editing metadata )
> 650 Initial testing feedback 

- app/assets/javascripts/lib/ui/component.js
- app/assets/javascripts/lib/ui/content/clone_modal.js
- app/assets/javascripts/lib/ui/content/publish_modal.js.erb
- app/assets/javascripts/lib/ui/content/revise_modal.js
- app/assets/javascripts/lib/ui/modal.js
- app/decorators/content/node_decorator.rb
- app/services/action_button_builder.rb
- app/views/content/_actions.html.erb
#650 #735 
Addressed comments in https://github.com/harvard-lil/h2o/pull/730#issuecomment-481448756
> Fix #650 comments

- app/webpacker/components/ResourceSectionWrapper.vue
> Add CSS for page-number class.

- app/webpacker/components/ResourceSectionWrapper.vue
- app/webpacker/components/TheResourceBody.vue
- app/webpacker/libs/html_helpers.js
- lib/html_helpers.rb
- package.json
- test/lib/html_helpers_test.rb
* Display footnote number and text on same line
* Fix linkage between footnote links 
#697 & #731
> Display footnotes 

- app/webpacker/components/ResourceSectionWrapper.vue
- app/webpacker/libs/html_helpers.js
> Restore aside filter to front end.

- lib/locales/en/landing.yml
Pointing to the better /most updated version of Fried's casebook
> URL change: Fried casebook

- app/assets/javascripts/lib/ui/content/export_modal.js.erb
> Export modal uses export yml.

- app/controllers/content/sections_controller.rb
> Prevent caching when exporting sections

- app/views/searches/_results.html.erb
> User search result page only shows count of public casebooks.

- app/controllers/searches_controller.rb
> Search page tab counts remain the same when switching tabs.

- .travis.yml
- docker-compose.yml
- docker/Dockerfile
Copy selenium's technique for installing matching versions of Chrome and Chromedriver, in Travis and in Docker. Devs on Macs, you are on your own 😉
> Fix Chrome/Chromedriver installation

- app/controllers/searches_controller.rb
- app/models/case.rb
- app/models/content/casebook.rb
- app/models/user.rb
> Search sort_by date sorts by created_at correctly.

- app/controllers/searches_controller.rb
- app/views/searches/_filters.html.erb
- app/views/searches/_tabs.html.erb
- app/views/searches/show.html.erb
> Search filters retain integrity during pagination 

- app/controllers/content/cases_controller.rb
> Only search for public cases locally before calling capapi.

- _python/main/templates/analytics.html
- _python/main/templates/base.html
- _python/main/templates/footer.html
- _python/main/templates/header.html
- _python/main/templates/includes/favicon.html
- _python/main/templates/index.html
Corrected base template, along with header and footer templates. Still missing some tags and link urls, but index looks good with this.
> Base template, header, footer 

- README.md
Separate badge lines for Rails and Django
> Tweak badges

- _python/main/models.py
Also do a bit of reorganization and commenting.
> Update ancestry when cloning.

- .travis.yml
Eventually we'll move this to the Circle config.
> Last (?) change for move of default branch

- _python/conftest.py
- _python/fabfile.py
- _python/search/create_search_index.sql
- _python/search/models.py
- _python/search/views.py
Add some basic tests for the /search page, and a `fab refresh_search_index` task that should run every 5 minutes.
> Search tests and refresh_search_index task

- _python/main/templatetags/rails_static.py
Oops, I broke this with my PR yesterday.
> Fix rails_static test

- _python/main/models.py
Closes https://github.com/harvard-lil/h2o/issues/950
If you add a new resource or section to draft, it isn't a `copy_of` another node... So, when merging, don't try to update the value of that field.
> Tweak for newly-added nodes when merging drafts

- _python/main/differ.py
- _python/main/models.py
Hopefully fixes 500 error with annotated export of https://opencasebook.org/casebooks/31832-contracts-cases-and-materials
> Handle annotation offsets past right edge of text

- _python/main/middleware.py
Add error reporting to diagnose malformed cookie error.
> Handle error reading rails cookie from python

- _python/Dockerfile
- docker-compose.yml
https://github.com/jgm/pandoc/releases/tag/2.8.1
> Bump pandoc to 2.8.1 on Django side

- _python/main/admin.py
- _python/main/models.py
- _python/main/templates/admin/main/case/change_form.html
- _python/main/templates/admin/main/default/change_form.html
- _python/main/templates/admin/main/textblock/change_form.html
- _python/main/templates/admin/main/user/change_form.html
Adds some links:
- casebooks from User detail page
- related resources from Case, TextBlock, and Default/Link detail pages
Restored ability to create new superusers and new caseadmins via the Django admin.
Tweaked a few other fields and labels.
> Minor admin improvements

- _python/config/settings/settings_base.py
- _python/main/templates/includes/analytics.html
Set `USE_ANALYTICS = True` in Django settings to enable this for a tier.
> Analytics.

- _python/config/context_processors.py
- _python/main/templates/index.html
- Add comment to frontend_urls function
- Fix logo.png path (fixed once and lost in the merge)
> Static asset tweaks

- _python/main/admin.py
[This filter](https://github.com/harvard-lil/h2o/pull/1005#discussion_r359057164) is preventing my dev server from working..... though h2o-experiment seems fine... not sure what to make of that. In any case, here is a PR to remove said filter.
> Tweak admin

- _python/config/settings/settings_base.py
- _python/main/admin.py
- _python/requirements.in
- _python/requirements.txt
- docker-compose.yml
Maybe we'll like it.
https://github.com/jmrivas86/django-json-widget
> Try a fancy JSON editor in the Django admin.

- _python/main/models.py
As discussed in slack, this refactors `casebook.clone` a bit to expose a separate `resource_or_section.clone_to(new_casebook)` function, which could be used for one-off customer service requests or later exposed for self-service.
I deleted the well-documented comment that `is_alias` is a legacy field along the way -- at this point I think it's self-evidently unused.
> Add clone_to method to copy nodes to new casebooks

- web/main/migrations/0033_auto_20200108_2000.py
- web/main/migrations/0034_auto_20200108_2017.py
> Resolve conflict in migration names.

- web/frontend/components/TheTableOfContents.vue
- web/frontend/store/modules/table_of_contents.js
- web/main/views.py
Also change delete button to be more verbose for sections
> Simplify TOC node moving logic to fix shuffling bugs

- web/frontend/pages/main.scss
- web/frontend/styles/cases.scss
- web/main/templates/case.html
Centers existing headers CAP-imported headers to more closely match CAP display style.
> Center case headers and remove extra citation

- web/frontend/components/TheResource.vue
- web/frontend/pages/vue_app.js
Resolves https://github.com/harvard-lil/h2o/issues/1069 and https://github.com/harvard-lil/h2o/issues/817
> Misc small fixes

- web/frontend/styles/casebook.scss
- web/main/models.py
- web/main/templates/casebook.html
- web/main/templates/casebook_credits.html
- web/main/templates/casebook_edit.html
- web/main/templates/includes/collaborators.html
- web/main/templates/includes/content_browser.html
- web/main/templates/includes/credits.html
- web/main/templates/includes/resource_tabs.html
- web/main/templates/includes/section_tabs.html
- web/main/templates/resource.html
- web/main/templates/resource_annotate.html
- web/main/templates/resource_credits.html
- web/main/templates/resource_edit.html
- web/main/templates/section.html
- web/main/templates/section_credits.html
- web/main/templates/section_edit.html
- web/main/urls.py
- web/main/views.py
Credits tab shows up for casebook, section and resource pages.
Factor out tabs so that they can appear consistently across pages.
> Add credits page to casebook

- web/main/templates/includes/preview_banner.html
> Only show banner when casebook is private

- web/main/models.py
- web/main/templates/includes/preview_banner.html
- web/main/views.py
If you can edit a casebook, it's always yellow/orange
If a casebook is public it's blue
If it's archived, it's grey.
> Adjust colors for consistency

- web/config/context_processors.py
- web/frontend/components/QuickAdd.vue
- web/frontend/components/TableOfContents/EntryTransmuter.vue
- web/frontend/components/TheTableOfContents.vue
- web/frontend/legacy/lib/ui/content/publish_modal.js
- web/frontend/libs/text_outline_parser.js
- web/frontend/libs/urls.js
- web/frontend/store/modules/table_of_contents.js
- web/main/models.py
- web/main/templates/base.html
- web/main/utils.py
- web/main/views.py
- web/search/utils.py
- web/search/views.py
Allow for cloning sections/casebooks via link
Allow for importing cases via link to H2O or cite.case.law
> Quick Add via Link
