- app/controllers/searches_controller.rb
- app/models/case.rb
- app/models/content/casebook.rb
- app/views/searches/show.html.erb
- Removes full case text from the search index, so e.g. "roe v. wade" returns only a single case result.
- Fixes a bug where the selected search tab would reset when the search query was changed.
- Adds a feature where if there are no search results for the current search tab, results for another tab are shown automatically.
> Better search results for case title search

- app/controllers/content/casebooks_controller.rb
- app/views/content/_actions.html.haml
- lib/locales/en/content.yml
- test/system/casebooks_test.rb
- Owner sees a revise button 
---> revise button takes you to edit details page (because of rails routing -- can fix later )
- Remove publish button from details view ( when in draft mode )
> Revise button in published view

- app/models/content/resource.rb
- lib/migrate.rb
- fixes a bug causing migrated annotations to appear in the wrong paragraph
> Migration bugfix prior to re-import of 100 casebooks dump

- app/views/content/_tabs.html.haml
- app/views/content/edit_details.html.erb
- app/views/content/table_of_contents/_edit.haml
* From table of contents Default ( this is actually a Link but legacy name ) should go to the Edit Details ( or Resource Details ) tab
** Default resources should not have an Annotate tab
** From table of contents  Case & TextBlock go to the Annotate tab
Closes https://github.com/harvard-lil/h2o/issues/162
> Correct tabs for resources 

- app/assets/javascripts/lib/ui/content/add_content.js.erb
* Remove modal-open class when modal destroyed
> Bug - background remained frozen after add-resource modal was closed 

- app/views/content/_tabs.html.haml
In draft casebook view, when viewing resource or section, both layout tab and resource/section tab had `active` class. This change removes 'active' class from layout tab when resource/section being viewed.
> fixed: active class in tabs in draft casebook view

- app/models/case.rb
This fixes a bug where `rake sunspot:reindex` produced a Solr error: 
```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":17},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"Error parsing JSON field value. Unexpected OBJECT_START at [2036], field=indexable_case_citations_text","code":400}}
```
That is, for cases with multiple citations, the citations were being presented to Solr as a list, which apparently it doesn't want to see for indexable items.
> Present case citations to Solr as string, not array

- config/initializers/rails_admin.rb
* looks like code was previously deleted and this was leftover.
> Remove rails_admin object_label_method 

- app/controllers/password_resets_controller.rb
- app/controllers/user_sessions_controller.rb
- app/services/url_domain_formatter.rb
- app/views/password_resets/edit.html.erb
* reset password was using css from old h2o / now uses same css as form in edit profile
* when adding a new link resource the file path isn't stripped out   
* logging out redirects to the root path --- was going back to the reset password page because of ajax
> Remove urldomainformatter code that removed file path.

- app/views/content/casebooks/export.haml
- app/views/content/resources/export.haml
- app/views/content/sections/export.haml
* in the export views it was checking for `content.formatted_headnote?` - now it just checks for `content.headnote?`
> Fix weird formatting in exported docs 

- app/controllers/searches_controller.rb
- test/fixtures/users.yml
- test/system/users_test.rb
Solr doesn't look for the `:verified_professor` field on the `cases` tab, but it does everywhere else (`/browse`, `casebooks`, `users`)
> Browse page shows only verified professors 

- app/views/content/casebooks/export.haml
- app/views/content/sections/export.haml
* exporting a casebook includes casebook headnote
* exporting a section includes section headnote
* resources already were exporting their headnotes 
BLOCKED - will need to update the osx & travis test files to make tests pass since exported files will now be bigger than what was previously stored
> Exporting docs & pdf has headnotes

- app/models/content/casebook.rb
Check for ancestry dependents.
The reason is because resources are cloned when cloning a casebook but annotations are not, so if a child references an ancestor's annotations it would cause a 500 if that annotation had been deleted.
> Add validation check to destroying a casebook 

- app/models/content/annotation.rb
- app/models/content/resource.rb
- app/services/merge_draft_into_published_casebook.rb
* replace begin block with transaction block
* raise exceptions for CRUD commands
* Instead of looking for new and updated annotations by data, do the logic directly 
* Destroy deleted annotations unpublished revisions when done 
* Remove unneeded exists_in_published_casebook methods
> Add transaction block around merging draft

- app/assets/javascripts/lib/requests.js
reload page if next location is on same page, otherwise replace the window location (for publishing a casebook for example).
> js requests can handle both cases 

- app/assets/javascripts/application.js
- app/assets/stylesheets/text.scss
- app/views/content/dashboard.html.erb
- app/views/content/layout.html.erb
- app/views/content/resources/show.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/casebooks.html.erb
- app/views/layouts/main.html.erb
This puts a skip link and a default target for that link in the layout files where it looks like skipping might come in handy.
If a particular view's "main" content is actually further down the page than the location of the default target, the view can provide a custom target via two steps:
1. Override the default by adding the line `<% content_for :custom_skip_target do %>i'm-arbitrary-text<% end %>` to the view.
2.  Place `<p id="main" tabindex="-1" class="sr-only">Main Content</p>` in the desired location.
This is kind of a zillion little commits: happy to rebase and combine them if you want!
> Skip links via layouts

- app/controllers/content/casebooks_controller.rb
- app/controllers/content/sections_controller.rb
- app/decorators/content/node_decorator.rb
- config/routes.rb
> Create specific revise routes so that sections and casebooks aren't cloned when editing a casebook from preview mode

- app/assets/javascripts/lib/ui/content/save_details.js.erb
- app/controllers/content/casebooks_controller.rb
- app/decorators/content/node_decorator.rb
- config/routes.rb
#337 
When creating a new casebook from scratch, two casebooks were being created. 
The casebook methods were pretty confusingly named. So I renamed / simplified them.
> Duplicate casebooks on create

- app/assets/javascripts/lib/ui/content/add_content.js.erb
- app/assets/javascripts/lib/ui/content/dashboard.js.erb
- app/assets/javascripts/lib/ui/content/delete_modal.js.erb
- app/assets/javascripts/lib/ui/content/export.js.erb
- app/assets/javascripts/lib/ui/content/publish_modal.js.erb
As reported by Adam, changes to some of the strings in `lib/locales` weren't showing up on the dev server, even when restarting. This is because they were getting cached in .js.erb files. To fix this, .js.erb files that include locales strings should also include a `depend_on` directive to tell Sprockets to regenerate the template when the locale file changes.
> Refresh .js.erb files on locale changes

- lib/locales/en/content.yml
- test/system/casebooks_test.rb
Resolves https://github.com/harvard-lil/h2o/issues/319 and addresses Becky's note about confusing UX of adapt -> search terminology
> Improved text on create-casebook modal

- Gemfile
- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/assets/javascripts/lib/ui/content/annotations/index.js
- app/assets/javascripts/lib/ui/content/annotations/placement.js
- app/controllers/content/annotations_controller.rb
- app/models/content/annotation.rb
TODO before peer review: move e.stopDefault() calls 
#301 
Previously clicking edit link for an annotation sent an empty request and didn't update the annotation. I created an `'edit-link'` case that renders the editLinkTemplate with the link filled in and the class has a listener `'update-link'` to update the annotation. 
I found the `Annotator` class confusing because it is so large so I reorganized the functions to be in more of an order of operations. 
The flow for this ticket is 
1. Click on ‘edit link’
2. `doAnnotationAction `triggered with case ‘edit-link’
3. Template `edit-link`
4. `editLinkTemplate()`
5. `submit .update-link'`
6. `updateAnnotation()`
Other:
* I refactored a few methods that were outside of the Annotator component into another file …
> Edit link annotations

- app/assets/javascripts/application.js
- app/assets/javascripts/lib/bootstrap/dropdown.js
- app/assets/javascripts/lib/ui/content/dashboard.js.erb
- app/assets/stylesheets/content/modals.scss
- app/assets/stylesheets/footer.scss
- app/assets/stylesheets/header.scss
- app/assets/stylesheets/layout.scss
- app/assets/stylesheets/mixins.scss
- app/views/layouts/_header.html.erb
- app/views/layouts/main.html.erb
- Hover/focus styles for the logo link
- "Create casebook" button is a real button
- The modal that it opens has all the behavior described here: https://github.com/harvard-lil/accessibility-tools/tree/master/code/modals
- The buttons/links are all the same size
- User picture removed from display per team decision!
- Dropdown coded up as a touch- and keyboard-usable Bootstrap dropdown
- Dropdown made white and full-width per Adam.
(The screenshot removed my cursor, which was hovering over "Edit", which is why that's gray. keyboard focus is on the button, which is why that has focus styles. )
Lemme know if you don't like anything about the way this looks!
Not in this PR:
- The modal accessibility fixes will need to be applied to every modal. So, I should abstract that out into a more …
> Header Accessibility

- app/models/content/casebook.rb
This was needed when resources were dependent on the original resource -- and so if you deleted a case in a casebook it would delete all of the copies of that case in the casebook's ancestry. 
Now deleting a casebook has no effect on other casebooks in it's lineage.
> Remove safeguard when deleting a casebook 

- app/assets/javascripts/lib/ui/content/annotations/elide.js
- app/assets/stylesheets/casebook.scss
- app/assets/stylesheets/content/annotations.scss
- app/models/content/annotation.rb
This makes the button that reveals/hides elided text into an html button so that it is accessible by keyboard, and it adds a label for screen reader users. It also adds a little hidden note at the end of elided text notifying screen reader users that they've reached the end of elided text. 
This still lacks some important features: all the buttons have the same label (how could I make them different? Paragraph number might be good, but I can't figure out how to expose paragraph number to the annotation code....), and, the labels are quite different visually and in the markup, which can/will be confusing both for people using Dragon Speak Naturally or similar, and for screen reader users following along with the H2O docs, which will certainly reference the visible label. But, I think I got …
> First pass, elision accessibility

- app/assets/javascripts/application.js
- app/assets/javascripts/lib/helpers.js
- app/assets/javascripts/lib/ui/content/annotations/replace.js
- app/assets/stylesheets/content/annotations.scss
- app/models/content/annotation.rb
I could not make this into a real html button. I could not get contenteditable to work reliably across browsers in combination with real buttons: hitting the spacebar presses the button, despite all the fancy javascript I could think of. It might be worth another try later... Instead, I added a bunch of stuff to make the `span` behave like a real button: added it to the tab order using tabindex, added event handlers for space and enter (which real buttons have automagically, when you assign a click handler), and added the `button` aria role. Good enough, methinks.
So, now it can receive focus. That's an accessibility win, and should help with the problem you are having related to page refreshes, until there's time to move to AJAX: we can use JS to set focus to an annotation on page load, …
> Replace button a11y first pass

- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/assets/javascripts/lib/ui/content/annotations/elide.js
- app/assets/javascripts/lib/ui/content/annotations/replace.js
I had noticed weird overlapping paragraph numbers in https://github.com/harvard-lil/h2o/issues/373; turns out this was caused by my failure to completely handle the toggling of replacement annotations for authors. 
This PR abstracts out the logic needed to toggle elisions/replacements into a function, and uses that function in the 3 spots toggling happens.
It should fix the overlapping paragraph numbers I caused, and should finish up https://github.com/harvard-lil/h2o/issues/300
> Replacement toggling

- app/assets/javascripts/lib/ui/content/clone_modal.js
- app/assets/javascripts/lib/ui/content/dashboard.js.erb
- app/assets/javascripts/lib/ui/content/export.js.erb
- app/assets/javascripts/lib/ui/content/publish_modal.js.erb
- app/assets/javascripts/lib/ui/modal.js
- app/assets/stylesheets/casebook.scss
- app/decorators/content/node_decorator.rb
- config/application.rb
- test/helpers/phantomjs/polyfills.js
- test/system/export_test.rb
This take the code from `dashboard.js.erb` that made THAT modal accessible, and abstracts it out into its own class, a subclass of Component.  So, now you can make any modal accessible by just inheriting from ModalComponent instead of Component (and making sure your template includes a tabindex of -1 at the top, and a label). 
This PR switches the clone modal and the publish modal to inherit from ModalComponent. Unfortunately I didn't get to any of the others yet.
This also makes the export button a one-click thing: export immediately instead of triggering a modal window.
> tweaked modals

- app/assets/javascripts/lib/ui/content/annotations/elide.js
- app/assets/javascripts/lib/ui/content/annotations/replace.js
- app/models/content/annotation.rb
https://github.com/harvard-lil/h2o/commit/7c335c41a4357c2a7124ec9611cfd3810c50ade9#diff-f87f5ba9f384eda55270ae286585b500L97 switched from plain spans to html buttons so that elisions could be toggled by people using input devices other than mice.
The export code is looking for spans (https://github.com/harvard-lil/h2o/blob/master/lib/htmltoword/xslt/h2o/export.xslt#L133), so this transformation wasn't run any more. I do not know why this test (https://github.com/harvard-lil/h2o/blob/master/test/system/export_test.rb#L21) did not catch the change.
Switching the export code to look for buttons instead of spans creates corrupt docx files. 
`¯\_(ツ)_/¯`
This PR switches back to a span, but retrofits the span to behave like a button.
> Use retrofitted spans instead of buttons so docx export works.

- app/models/content/section.rb
- lib/locales/en/content.yml
Remove ordinal-based default titles in favor of "Untitled section" default title.
Addresses #323
> Simplify default section titles to avoid confusion

- config/routes.rb
This also resolves a deprecation warning for Rails 5.2. Closes #344.
> Add catchall to render 404s

- app/decorators/content/node_decorator.rb
A few more tweaks to this button labeling issue, to ensure that when previewing any draft casebook/section/resource, the button label says "Return to Draft" rather than "Revise."
"Revise" button applies only when something is published and the author wants to revise it, and that button triggers build of a draft.
> Preview button label

- app/assets/javascripts/lib/ui/content/annotations/placement.js
#511 
and run query to replace `\r\n` when deploying
> Add chars for h2 tags, but not for blockquotes.

- app/assets/javascripts/lib/ui/content/export_modal.js.erb
- app/assets/stylesheets/content/annotations.scss
- app/decorators/content/node_decorator.rb
- app/models/content/casebook.rb
- app/models/content/resource.rb
- app/models/content/section.rb
- app/views/content/resources/_embed.haml
- lib/locales/en/content.yml
- test/files/osx/test_export_casebook.docx
- test/files/osx/test_export_section.docx
- test/files/osx/test_export_section_2.docx
- test/files/travis/test_export_casebook.docx
- test/files/travis/test_export_section.docx
- test/files/travis/test_export_section_2.docx
Address comments in #552 
- styling to elisions toggle button
- don't show export modal when there are no annotations in casebooks, sections and resources 
- show toggle button for text blocks
> Don't show export model option when no annotations. 

- app/mailers/notifier.rb
- app/models/content/resource.rb
- app/views/notifier/missing_annotations.html.erb
Need to get more data on what kind of annotations are failing. For now this will show the user the page and email admin the info of what annotations aren't able to find their placement
#585
> Send admin email when annotations aren't shown, still show user page.

- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/webpacker/components/AnnotationHandle.vue
Chrome places the wrapper `<span>` at the top left of the parent
element, causing an undesired result from
getBoundingClientRect(). Calculating from the `<button>` consistently
returns the desired result.
> Calc handle offsets using button el

- app/assets/javascripts/lib/ui/content/annotations/index.js
It appears this was a misuse of `$().ready` that became important when
jQuery was upgraded. In short, `ready` should only be used with
`$(document)` and should not be used to test whether an element on the
page has become ready. In this case, it was being used in hopes of
triggering the callback only when the body contained a class that's
applied for logged in users.
Here is the relevant jQuery documentation:
https://api.jquery.com/ready/
> jQuery offers several ways to attach a function that will run when the DOM is ready. All of the following syntaxes are equivalent:
> 
> $( handler )
> $( document ).ready( handler )
> $( "document" ).ready( handler )
> $( "img" ).ready( handler )
> $().ready( handler )
> As of jQuery 3.0, only the first syntax is recommended; the other syntaxes still …
> Prevent annotations when logged out.

- Gemfile
- Gemfile.lock
- app/views/content/_collaborators.html.erb
- config/initializers/rails_admin.rb
Also ckeditor wasn't showing up in admin previously and now it is 
Test
Rich text editors have same functionality overall 
- Editing a headnote and save
- Editing text block content
- ^ Both look correct in preview
- rich text editor box shows up in admin for case text, casebook headnotes, text blocks
> Upgrade ckeditor as per secuirty vulnerbility

- app/assets/stylesheets/casebook.scss
Before switching to webpack, this property was not vendor prefixed, leading to
it having an effect in Chrome and Safari but not Firefox. After the
switch, the vendor prefix meant Firefox was correctly disabling select
on paragraph numbers but this lead selections that spanned
paragraphs to register their end range as the enclosing `div.case-text`
rather than the actual paragraph in which the selection ended. Not
sure why Firefox behaves this way -- maybe there's a proper work
around to that behavior -- but this commit restores the pre-webpack
behavior for better or worse (seems to be for better).
Side note: I couldn't get `/* autoprefixer: ignore next */` to
work as outlined in their readme, hence the `off` then `on` statements.
> Disable prefixing for user-select to sidestep Firefox bug

- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/assets/javascripts/lib/ui/content/annotations/index.js
- app/assets/javascripts/lib/ui/content/annotations/placement.js
- app/assets/stylesheets/casebook.scss
- yarn.lock
When selecting across nested elements and elements with `user-select:
none`, Firefox splits the selection across multiple ranges whereas
Chrome and Safari represent them as a single range. This change
accommodates both approaches.
Closes #610
> Modify placement logic to handle multiple ranges

- app/assets/javascripts/lib/ui/content/annotations/annotator.js.erb
- app/controllers/content/annotations_controller.rb
- app/webpacker/components/AnnotationHandle.vue
- test/system/annotations_test.rb
- can input a link annotation without htto (ie: `asdasdasd.com`) and it adds http while creating it, resulting in `http://asdasdasd.com`
- can input a standard https link and the result matches the input (input: `https://asdasd.com`, result: `https://asdasd.com`
- can input an incorrect url (ie: `asdasdasd`) and after saving, you can manually edit the link to be correct. 
#433
> HTTP requirement doesn't pop up when creating a link annotation

- app/controllers/content/casebooks_controller.rb
- app/models/content/casebook.rb
- app/models/content/child.rb
- config/initializers/rails_admin.rb
- test/system/admin_test.rb
https://github.com/harvard-lil/h2o/pull/620#issuecomment-447063264
There should alway be one user with attribution (perhaps whatever user is in the first slot of names on admin collaborator page, if none have their checkbox checked?)
#532
> One collaborator always has attribution 

- app/webpacker/components/TheResourceBody.vue
- app/webpacker/libs/html_helpers.js
Some of the Ruby functions aren't needed because of the way we're
selecting elements in the JS. For instance, we don't need to filter
out comment nodes because we're using el.children which only returns
element nodes.
> Add JS versions of html_helpers.rb

- app/models/content/resource.rb
- app/services/apply_annotation_to_paragraphs.rb
- app/views/content/casebooks/export.haml
- app/views/content/resources/export.haml
- app/views/content/sections/export.haml
- app/webpacker/components/NoteAnnotation.vue
- app/webpacker/components/ResourceSectionWrapper.vue
- app/webpacker/components/TheResourceBody.vue
- lib/htmltoword/xslt/no-annotations/base.xslt
- lib/htmltoword/xslt/no-annotations/cleanup.xslt
- lib/htmltoword/xslt/no-annotations/h2o/export.xslt
- lib/htmltoword/xslt/with-annotations/cleanup.xslt
- lib/htmltoword/xslt/with-annotations/h2o/export.xslt
Since this code is now only used for exports, we can remove much of the logic and markup associated with front-end rendering. This also fixes #660.
@cgruppioni I wanted to remove the `include_annotations` flag from `apply_annotation_to_paragraphs` (and a few other places; not everywhere) but couldn't totally figure out why there are two export code paths there to begin with. Why not just bypass applying annotations entirely rather than execute `apply_annotation_to_paragraphs` while passing a flag that actually doesn't apply annotations to paragraphs?
> Remove cruft

- app/models/case.rb
- app/views/searches/_results.html.erb
- test/system/cases_test.rb
#689 
Name abbreviation shows in:
> CAP API cases render with name abbreviation instead of full name 

- Dockerfile
- README.md
- config/database.yml
- docker-compose.yml
- init.sh
- test/helpers/drivers.rb
This PR adds the ability to spin up a disposable, working development environment via Docker.
It's pretty clunky at present (mounts the entire `.` into the web container, which includes the whole `./tmp` directory; unusual work around for `node_modules`, etc.), but should functionally operate like a local installation.
This should not affect anybody's local installations: everything should still work fine.... Since I don't have a working local installation, I can't personally confirm that https://github.com/harvard-lil/h2o/compare/master...rebeccacremona:docker-setup?expand=1#diff-e31bdf70b15c8f84344c332efe06900d is correct, but I have compared the error messages: they are identical if I run a) WITHOUT my changes, and b) with my changes, but with the Docker-specific env vars unset. I'm …
> First pass at a Dockerized development environment.

- README.md
- docker/init.sh
- docker/run.sh
- docker/test.sh
`bash docker/init.sh -f ~/database.dump`
We're getting some (repeatable) errors when loading some recent data. I'm relatively sure it's not a problem with the process, so am committing an error-swallowing workaround for the time being. We'll definitely want to remove that workaround once we diagnose and fix the issue.
> Option to initialize dev database w/ data.

- config/environments/development.rb
Fixes warning from Rails dev server when running in Docker:
```
Cannot render console from 192.168.208.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
```
> Allow the interactive, browser-based debugging console when Dockerized.

- docker-compose.yml
- package.json
- yarn.lock
yarn install into a clean `node_modules` folder consistently reports:
> [3/4] Linking dependencies...
> warning "vue-jest > @babel/plugin-transform-modules-commonjs@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "@rails/webpacker > pnp-webpack-plugin > ts-pnp@1.0.0" has unmet peer dependency "typescript@*".
> warning " > rails-erb-loader@5.5.0" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".
> warning " > vue-loader@15.6.2" has unmet peer dependency "css-loader@*".
> warning " > vue-loader@15.6.2" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
> warning " > babel-jest@24.1.0" has unmet peer dependency "@babel/core@^7.0.0".
> warning " > vue-jest@4.0.0-beta.2" has unmet peer dependency "@babel/core@7.x".
> warning "vue-jest > …
> Handle unmet peer dependencies.

- app/webpacker/components/NoteAnnotation.vue
> Hide note-content-wrapper unless annotation is not new.

- app/webpacker/components/AnnotationBase.vue
- app/webpacker/components/ContextMenu.vue
- app/webpacker/components/LinkAnnotation.vue
- app/webpacker/components/LinkInput.vue
- app/webpacker/components/NoteAnnotation.vue
- app/webpacker/components/TheAnnotator.vue
#674 
**Testing plan**
There are no noticeable changes for users, but a lot of the functionality under the hood has changed. So compare annotating to production and make sure that everything is still fully functional
> 674 Move the annotator logic into single components

- app/decorators/content/node_decorator.rb
- config/initializers/rails_admin.rb
- db/migrate/20190411201647_add_cloneable_to_casebooks.rb
- db/schema.rb
Admin can uncheck cloneable field ( all casebooks are able to be cloned by default ) to hide clone button from unauthorized users ( casebook collaborator or an admin user )
> Add cloneable field to casebook

- .travis.yml
- README.md
- Rakefile
- config/spring.rb
- config/webpack/environment.js
This PR has a few tweaks suggested by the explorations in https://github.com/harvard-lil/h2o/issues/744 and https://github.com/harvard-lil/h2o/issues/743.
1) It suppresses some of the automatic calls to `yarn install`.
If merged, stage/prod deployments should be altered to include an explicit call to `yarn install --frozen-lockfile --check-files`. This command defaults to `NODE_ENV=development`; if you want only production requirements installed, set `NODE_ENV=production`.
2) It sets Travis to compile assets without the assistance of Spring, to prevent unwanted output and prevent spurious reports that asset compilation has failed. 
3) It adds, in comments, another option for suppressing unwanted output locally. If stage/prod calls to `precompile:assets`, which do not (should not!) use …
> Tweaks suggested by node debugging process

- config/webpacker.yml
This appears to do the job: without this line, locally, calls to `precompile:assets` do NOT detect changes to scss; with it, changes are detected and new packs/bundles are emitted!
I tried running locally with Guard, and with `rails s`, before and after, and the addition doesn't appear to break any of those setups.... Though again, as a newcomer to this project, I'm not sure.
> Watch for changes in css/scss when precompiling assets.

- app/assets/stylesheets/pages.scss
This underlines links on about, terms-of-service, etc. `!important` because some other code is using `!important` to remove the underlines....
We can reverse this if we want, it's just to test the build.... Though I'd argue that most links should be underlined 😉
> Tweak css to test build process

- .travis.yml
- docker-compose.yml
- docker/Dockerfile
I cannot imagine how I landed on version 2.41 of Chromedriver in my initial installation.... this pins Chrome to the version being distributed today via `http://dl.google.com/linux/chrome/deb/ stable main` and the matching version of Chromedriver. Works in Docker; syntax may be incorrect for Travis.
We're not positive this is precisely correct for the long run; I'll definitely readdress if this technique proves to be brittle.
> Pin version of Chrome and Chromedriver.

- .gitignore
- README.md
- config/webpack/environment.js
- config/webpack/test.js
- package.json
- test/javascript/components/ResourceSection.test.js
- test/javascript/libs/html_helpers.test.js
- test/javascript/libs/resource_section_parsing.test.js
- test/javascript/mocha_setup.js
- test/javascript/test_helpers.js
- yarn.lock
This ensures that the JS we're testing is built using the same build
tools that we use for production. Our previous testing framework,
Jest, was slightly faster due to the lack of a webpack build step, but didn't
compile Vue files identically to that of production, leading to the
possibility of meaningful differences arising.
> Switch JS tests to use mocha-webpack

- app/webpacker/components/TheResourceBody.vue
- lib/vue/ssr.js
- lib/vue/ssr.rb
- package.json
- yarn.lock
#677 
Usage via Ruby:
```ruby
resource = Content::Resource.last # grab a Resource with a Case
Vue::SSR.render(resource.resource.content, resource.annotations) # => html string
```
This currently uses webpack to build the ssr.js file on each
invocation, which is inefficient but good for dev. Given that we're
going to be pairing this with PANDOC work, it would make sense to
optimize this with a proper deploy-time build of ssr.js at that point.
> Add basic server side rendering of resources via Vue SSR

- .travis.yml
- app/controllers/password_resets_controller.rb
- app/models/case.rb
- app/models/default.rb
- app/models/text_block.rb
- app/views/content/resources/_embed.erb
- app/views/content/resources/show.html.erb
- app/views/content/show.html.erb
Subsequent to the recent discussion about user-supplied `<img src="">`, Jack was wondering how we handle other user-supplied values throughout the app. Investigation proved we could benefit from more careful handling of headnotes, and more careful handing of titles, usernames, and email addresses in a handful of spots. 
This PR runs headnotes through [Rail's sanitizer](https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails/html/sanitizer.rb#L61) before rendering, and adds html-escaping in other places where user-supplied text is subsequently marked as `html_safe`. 
Experimentation suggests that Vuejs is stripping `script` tags from cases and textblocks before rendering. It would be good to get another set of eyes on this, especially from a dev more experienced with Vue to …
> Sanitize or escape user-supplied values

- app/views/content/casebooks/export_pandoc.haml
This fixes the bug Brett found w/Pandoc export on dev, preventing casebook 114225 from exporting properly.
> Handle XML special chars like & in Table of Contents.

- app/services/merge_draft_into_published_casebook.rb
When you want to edit an already-published casebook, you first make a draft, which is in actuality a complete copy of the whole textbook. If you delete one of the draft's annotations, there is code that matches the draft annotation with the original annotation, and makes a note in the table UnpublishedRevisions, "be sure to delete the original annotation, when publishing the draft!" If there is an annotation on characters 10-20, and make a draft, delete that annotation, then create another annotation in exactly the same spot, and then delete THAT one, it will make TWO notes in UnpublishedRevisions: one for each deletion. During publication/merging, this loop errors on the second attempt to delete the original annotation: `find` errors if no record is present; `find_by` does not.
> Handle repeated deletions of annotations in drafts

- _python/config/settings/settings_dev.py
- docker-compose.yml
- docker/h2o.conf
This exposes the application locally at port 8003, manually whitelisting routes we want to send to Django in `docker/h2o.conf`. To try it, run, in three separate terminals,
```
docker-compose up
bash docker/run.sh
docker-compose exec python ./manage.py runrver 0.0.0.0:8000
```
> First pass at whitelisting Django routes

- .gitignore
- _python/conftest.py
- _python/main/models.py
- _python/main/views.py
- _python/requirements.in
- _python/requirements.txt
- _python/setup.cfg
- docker-compose.yml
First pass at adding a testing framework. Tests can be run with `$ pytest` in the _python directory, from the python docker container.
I didn't write a ton of tests, but (for purposes of discussion) included docstring tests for a couple of model functions and a view function as examples of how we could do those. The other place tests can live of course is in files like `main/tests/test_views.py`, which may be better for some things, but I wanted to see what the doctest version looked like.
I always end up hating test fixtures, so this is yet another reinvention of that! All the fixtures live in conftest.py. The file includes three sections:
- Factories, which use a lot of subfactories and relatedfactories so you can e.g. create a casebook and it comes along with a new user who owns it. …
> Add pytest integration

- _python/.gitignore
- _python/Dockerfile
- _python/config/settings/settings.py.example
- _python/config/settings/settings_base.py
- _python/config/settings/settings_dev.py
- _python/config/urls.py
- _python/conftest.py
- _python/main/middleware.py
- _python/main/models.py
- _python/main/templates/includes/table-of-contents.html
- _python/main/utils.py
- _python/main/views.py
Misc work from yesterday:
- sql profiling helpers:
- postgresql-client auto-installed in python docker env
- django-debug-toolbar will be used if installed via `pip install django-debug-toolbar`
- add logging config and example logger in `settings.py.example` to log all sql queries
- expanded test fixtures, including `full_casebook` with a section and 6 resources (this might not be right yet!) and an `admin_user`
- hack our auth middleware so test client can make authorized requests like `client.get(url, as_user=admin_user)`; use to expand tests on the dashboard page
- add `ContentNode.objects.prefetch_resources()` so each fetched content_node will come with `.resource` prepopulated without a separate sql query; use to speed up the TOC page
- replace `blank=True, null=True` in …
> Python stuff: resource prefetch, django-debug-toolbar, tests with logged-in users

- _python/config/settings/settings.py.example
- _python/config/settings/settings_base.py
- _python/config/settings/settings_dev.py
- _python/main/templates/base.html
- _python/main/templates/includes/favicon.html
- _python/main/templates/index.html
- _python/main/templatetags/rails_static.py
- _python/requirements.in
- _python/requirements.txt
- _python/static/README.txt
- docker-compose.yml
This avoids the temporary hack we had of loading static assets from production URLs. Django will now use `whitenoise` to serve static assets, serving the Django assets under `/static/` and also anything in the Rails public/ folder under `/`. So Rails files will now be available as `http://h2o-dev.local:8001/robots.txt`, `http://h2o-dev.local:8001/packs/css/main-1a2b3c4d.css` etc, and Django assets for the admin and django-debug-toolbar and anything else will also work.
This opens up the ability to gradually migrate any assets to `/static/` if they are only referenced from the Django side.
Rails assets have hashes in the filenames that might change and shouldn't be included in our templates. So this also includes a `rails_static` templatetag that looks up hashed filenames, inserting …
> Python: serve Rails static assets in Django using whitenoise

- _python/config/settings/settings_base.py
- _python/config/settings/settings_dev.py
- _python/main/models.py
- _python/main/utils.py
- Add a casebook.merge_draft function, not yet exposed through views (though I do have some WIP locally on the view to go along with this). This uses the strategy Becky and I discussed where casebook attributes are copied over, old casebook assets are deleted, and draft content nodes are pointed to the published casebook. I'm sure I missed something!
- Coming along for the ride: `fix_after_rails("some todo message")` and `fix_before_deploy("some todo message")`, to use in place of our current `# TODO` comments. `fix_before_deploy` asserts that `settings.NOT_ON_PRODUCTION` has been set to true, so it will make a fuss if we whitelist a route we shouldn't. `fix_after_rails` is just a no-op, but making it a function ensures that we're consistently using the same string and can find them all …
> Merge draft casebooks

- lib/differ.rb
- test/lib/differ_test.rb
This is meant to address the following error that was being thrown in production:
```ruby
undefined method `[]' for nil:NilClass
​
lib/differ.rb:69:in `get_delta_at_offset
```
I believe this was caused by annotations with "impossible" offsets (i.e. greater than the length of the text). This PR causes those offsets to be left unmodified when calculating new offsets on text updated.
> Remove max bounding in search function to handle impossible offsets

- _python/conftest.py
- _python/main/models.py
- _python/main/serializers.py
- _python/main/templates/base.html
- _python/main/templates/casebook.html
- _python/main/templates/casebook_edit.html
- _python/main/templates/includes/action_buttons.html
- _python/main/templates/includes/breadcrumbs.html
- _python/main/templates/includes/content_browser.html
- _python/main/templates/includes/table-of-contents.html
- _python/main/templates/resource.html
- _python/main/templates/resource_annotate.html
- _python/main/templates/resource_edit.html
- _python/main/templates/section.html
- _python/main/templates/section_edit.html
- _python/main/urls.py
- _python/main/views.py
- app/assets/javascripts/lib/ui/content/save_details.js
- app/services/action_button_builder.rb
- app/views/layouts/_favicon.html.erb
The goal of this PR was to port over the logic for which "action buttons" (e.g. Save, Publish, Clone, Export, etc.) to display on which pages.
This proved a very useful approach for starting to build out the rest of the app: action buttons appear on virtually every page. So, this PR includes a number of partially-implemented views, and, by way of the buttons, exposes much as-yet-unported functionality. For instance, you can click the "publish" button... but it doesn't publish yet! There are no form fields on the pages that should have forms. Etc. I would have preferred not to merge in these half-finished pages... But, I think that's probably impossible short of finishing the port in one go :-) I believe it is unambiguous what has been built and what hasn't. I've included lots of TODOs and …
> Action buttons; refactoring; partial "edit" pages.

- _python/conftest.py
- _python/main/admin.py
- _python/main/models.py
- _python/test_helpers.py
- Add the `ContentNode.content_tree__move_to` method, as well as a bunch of supporting methods
- Refactor some ancestry methods to start with `version_tree__` (I don't think I hit all of the methods that could use this new naming scheme though)
- Add `-v -v` option for `assert_num_queries`
> Can move nodes in the content tree

- _python/Dockerfile
- _python/requirements.txt
- docker-compose.yml
The latest pip is incompatible with our previous version of pip-tools. This updates pip-tools to the latest, and also freezes the pip version in the Dockerfile so we won't get this kind of mismatch in the future.
> Freeze pip version; update to compatible pip-tools version

- _python/main/templates/section_edit.html
You can publish a draft (revision of a previously-published casebook) while viewing one of its sections. For that modal/javascript to work, it turns out that the id of the parent casebook has to be present in the html, as per this PR. 
This is interesting.... do we want to have functional tests for each action button on each page....
Ugh.
> Publishing from a draft's "section" page

- _python/conftest.py
- _python/main/admin.py
- _python/main/differ.py
- _python/main/models.py
- _python/main/utils.py
- _python/requirements.in
- _python/requirements.txt
- _python/test_helpers.py
- docker-compose.yml
This ports over the code from differ.rb and adds code to update annotations when Case or TextBlock content is modified.
There are two new sources of error introduced during the port (in addition to the usual may-not-have-done-it-right source):
(1) lxml may extract text from html differently from the Ruby html parser
(2) I modified the internal data structure from differ.rb so it looks like:
```
offsets = [0, 5, 13, 23]  # the offset beginning each range in the first string
deltas = [RelativeDelta(0), AbsoluteDelta(5), RelativeDelta(-8), RelativeDelta(-2)]  # how to adjust offsets within each range 
```
This basically precalculates the delta to apply for every given offset. The `diffs` data structure in the current ruby instead looks like this:
```
[(0, 'Kids ', Range(min=0, max=5), …
```
> Shift annotations when underlying text is edited

- _python/config/settings/settings_base.py
- _python/main/admin.py
- _python/main/templates/includes/header.html
- _python/main/templates/index.html
- _python/main/templates/pages/faq.html
- _python/main/urls.py
- _python/main/views.py
This will fix the Sign Out link that is currently broken on python pages on h2o-experiment and prod:
When deploying, you can add `/user_sessions/logout/` to the nginx config -- the ruby pages use a different route, so won't be affected.
> Fix logout link for python pages

- .gitignore
- _python/config/settings/settings_base.py
- _python/config/settings/settings_pytest.py
- _python/conftest.py
- _python/main/models.py
- _python/main/test/test_permissions.py
- _python/main/test/test_permissions_helpers.py
- _python/main/urls.py
- _python/main/views.py
- _python/search/models.py
- _python/setup.cfg
This PR adds a test that ensures that each view in `main.urls` is decorated with one or more permissions tests. A permissions test looks like this:
`@perms_test({'method': 'post', 'args': ['casebook'], 'results': {302: ['casebook.owner', 'admin_user'], 403: ['other_user'], 'login': [None]}})`
... which is an assertion that, if you post to the decorated view with the url param `casebook`, you should get a 302 redirect as the casebook's owner or admin, a 403 permission denied as an unrelated user, and a login redirect if not logged in.
The strings like 'casebook.owner' use pytest's fixture resolution combined with Django's template variable syntax, so they're pretty flexible and robust.
@perms_test can also work as a basic success test for the view itself. If the docstring was just going to …
> Add mandatory @perms_test decorator for views

- _python/main/urls.py
Note that because these were permanent redirects, you may have a /pages/about -> /about redirect hanging around in your browser that confuses things when testing.
> Re-add /pages/ to template urls for now

- _python/conftest.py
- _python/main/models.py
- _python/main/test/test_export.py
Tweak export annotation logic so annotations avoid wrapping adjacent tags, as well as tweaking the logic for overlapping annotations. Add tests for both scenarios.
> Export annotations try to avoid wrapping adjacent tags

- _python/fabfile.py
- _python/search/create_search_index.sql
- _python/search/models.py
This changes our substantive search results in two ways:
- only include casebooks that have a user relationship with `has_attribution=True`; this will filter out some duplicate results
- casebook search results include hits based on author attribution or affiliation (so searching casebooks for "lessig" will return all lessig-authored casebooks)
Basically casebook search will include slightly more correct results and slightly fewer incorrect results.
DEPLOYMENT: This also adds a `fab refresh_search_index`, which can be run in crontab instead of the existing `fab create_search_index`. (It will fall back to create if the index doesn't exist yet, so should be safe to run on new dbs as well.) This optimization is slightly faster and also won't block any search queries that happen to be run at …
> Tweak search results; faster search index update

- _python/conftest.py
- _python/main/admin.py
- _python/main/models.py
- _python/main/templates/includes/content_browser.html
- _python/main/test/test_permissions_helpers.py
- _python/main/utils.py
- _python/main/views.py
The headline features here are to have user permissions for casebooks also get applied to their drafts (and vice versa) in the admin, and to improve the performance of some admin screens. This moved a bunch of stuff around under the hood but hopefully didn't change much actual functionality. Details:
- Add cached properties `draft` and `draft_of` to `Casebook`, which work more or less like they will if we turn the relationship into a one-to-one field in the future
- Drop the existing `drafts()` method
- Saving a casebook in the admin edit screen copies its user collaborators to its draft/draft_of
- Refactor admin.py a bit with an edit_link() helper
- Optimize some admin.py screens with get_queryset 
- Have the casebook collaborator methods (like `.owner`) always use …
> Admin query optimization and casebook permissions copying

- _python/conftest.py
- _python/main/models.py
This PR adds code for deleting Default/Link and TextBlock resources when their parent Resource/ContentNode is deleted, and for deleting a draft when its parent Casebook is deleted. 
It also does a bit of refactoring: the code for efficiently deleting unneeded Defaults/Links and TextBlocks, once part of the `merge_draft` method, was factored out into a reusable helper, and the `delete` methods for Sections and Resources, very similar, were combined into a single method in `SectionAndResourceMixin`. The tests for that method are quite long... good enough for now?
This is more thorough than the Rails app. 
We should consider cleaning up the DB at some point, deleting all Links, TextBlocks, and Casebooks, that appear to be orphaned.
> More thorough deleting

- app/webpacker/components/TheResourceBody.vue
Some existing h2o cases use `class='page-number'`, and cap delivers html with `class='page-label'`
This PR assigns same styles to both classes.
> update class for in-text pagenumbers to match CAP

- _python/main/templates/includes/collaborators.html
Closes https://github.com/harvard-lil/h2o/issues/951. (Attributor method now returns list, not queryset.)
> Fix casebook attribution in template.

- _python/main/admin.py
Disable add and delete buttons in Django admin, except for:
- add user
- add and delete collaborators for casebooks
- add and delete annotations when editing a resource
We can add in any other exceptions as needed.
> Disable add and delete in django admin

- app/webpacker/components/TheResourceBody.vue
Tweak the paragraph number selector so it can show paragraph numbers in CAP html without stripping section tags and stuff.
Also includes a tweak to the blockquote styles so there aren't linebreaks between consecutive linebreaks.
> Show paragraph numbers in CAP html

- _python/config/settings/settings_base.py
- _python/main/admin.py
- _python/main/templates/registration/password_change_done.html
- _python/main/templates/registration/password_change_form.html
- _python/main/templates/registration/password_reset_complete.html
- _python/main/templates/registration/password_reset_confirm.html
- _python/main/templates/registration/password_reset_done.html
- _python/main/test/test_permissions.py
1) Now that auth-related flows are available via python, remove the customizations in the Django Admin
2) Fix up a few templates. For example,
Before:
After:
3) Fix a button label.
4) Remove the Django setting that customizes `redirect_to_login`, so redirection works correctly.
> Tweaks to new user-related pages.

- app/webpacker/components/TheResourceBody.vue
https://github.com/harvard-lil/h2o/pull/969/files should work, but something funny is happening with the `:not` selector.... verified by playing around with adding borders to elements: The selector inside `:not()` has to be simple (`p`, or `div`, not `p.foo` or `p, span`) or the entire block of css gets dropped.
Switching to `:not(section)` seems to work.
> Get paragraph numbers back by tweaking css

- docker-compose.yml
You will need to `docker volume rm h2o_db_data` before rebuilding.
> Update Postgres to 9.6.16

- _python/config/settings/settings_base.py
- _python/main/admin.py
- _python/main/apps.py
- _python/main/models.py
This lets our UserAdmin inherit from Django's built-in UserAdmin, which comes along with a free change-password form. Also overrides the new-user form to set a random password, which means the reset password form will work.
*Suggested workflow for creating accounts that don't end in .edu:*
- Create the account in the Django admin, with no password and with verified_email off
- Either use the forgot-password form or tell the user to use it, and they should then be able to verify their email, set a password, and get the welcome email as normal
Fixes #999
> Support add-user and change-password in admin

- _python/conftest.py
- _python/main/admin.py
- _python/main/forms.py
- _python/main/templates/admin/main/user/change_form.html
- _python/main/urls.py
- _python/main/utils.py
- _python/main/views.py
This PR addresses [my comments](https://github.com/harvard-lil/h2o/pull/1005#issuecomment-566782502) on the PR to "Support add-user and change-password in admin"
- It switches the admin to display `crypted_password` instead of `password`, pending further changes to our auth setup.
- It arranges for users without verified email addresses to receive a new verification email if they attempt to reset their password
- It adds a button to the Django admin letting admins trigger the sending of a verification email (for unverified users) or a password reset email (for verified users).
And yes.... that did take all day 😁
> Tweaks for adding users via the admin

- README.md
- docker/init.sh
In Rails land, `init.sh` created test and dev databases, and then, if run with `-f` and provided a pg_dump file, it would seed the database.
Now there is no need to manually create any databases: we only need one, and we are using the default that comes with the postgres docker image.
This PR updates the README and tweaks the init script. 
It retains use of the `-f` flag, which is a slightly awkward API, now, because it is mandatory.... Shall I remove it? I am pretty rusty on bash script argument parsing, and am a little hesitant to dive back in, especially if we think we might want the existing framework to parse more flags in the future (for instance, running with or without `disable-triggers`). But, I am happy to do so if this feels too peculiar!
> Correct DB initialization and instructions

- docker/init.sh
I hubristically merged https://github.com/harvard-lil/h2o/pull/1018 before attempting to run migrations..... which failed.
They failed because the initialization script had special handling for two Rails-only tables, `ar_internal_metadata` and `schema_migrations`. Previously, prior to the pg_restore move, Rails would create an empty, but fully migrated database, and this script would attempt to load data into the already-present tables. The database creation move would itself populate `ar_internal_metadata` and `schema_migrations`; the data import therefore intentionally skipped those tables. But now, we don't want any of that special handling: we want the whole DB, as is.... so that we can run migrations, the first of which drops all Rails-only tables, including `ar_internal_metadata` …
> Further correct database initialization script.

- web/frontend/styles/searches.scss
Works around a fun webkit bug where a tags simultaneously do and don't have focus.
> Show generic focus style for search results list

- web/frontend/components/ReplacementAnnotation.vue
- web/main/templates/casebook_page.html
- web/main/views.py
Also properly throw 404 instead of 500 when looking up nonexistent casebooks.
> Workaround for FFDevEdition contenteditable oninput issue
